name: 更新文件名

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: run py script
      run: |
        python wordlist_from_dir1.py
    - name: run py script
      run: |
        python wordlist_from_dir.py
    - name: commit
      run: |
        git config --global user.email mrwq@qq.com
        git config --global user.name mrwq
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
